apiVersion: v1
kind: ConfigMap
metadata:
  name: notification-service-config
  namespace: app
  labels:
    app: notification-service
data:
  # Configuraciones generales no sensibles
  LOG_LEVEL: "info"
  SERVICE_NAME: "notification-service"
  # Configuraci√≥n de emails
  FROM_EMAIL: "felimarra9@gmail.com"
  TO_ADMIN: "felipe.marra@estudiantes.utec.edu.uy"
