apiVersion: v1
kind: Secret
metadata:
  name: notif-smtp-secret
  namespace: prod
type: Opaque
stringData:
  SMTP_HOST: pro.turbo-smtp.com
  SMTP_PORT: "465"
  SMTP_USER: "<TU_USER_TURBOSMTP>"
  SMTP_PASS: "<TU_PASS_TURBOSMTP>"
  FROM_EMAIL: "noreply@example.com"
  TO_ADMIN: "admin@example.com"