apiVersion: v1
kind: Secret
metadata:
  name: smtp-secret
  namespace: prod
type: Opaque
stringData:
  SMTP_HOST: "pro.turbo-smtp.com"
  SMTP_PORT: "465"
  SMTP_USER: "2261e7cd12c99b4e36e4c423569dc33d"
  SMTP_PASS: "a6wtf5O8z3Y107dLrsnbZDuV4ejmB9Xy"
  SMTP_FROM: "crisreyvpi123@gmail.com"
