apiVersion: v1
kind: Secret
metadata:
  name: smtp-secret
  namespace: app
  labels:
    app: notification-service
type: Opaque
stringData:
  SMTP_USER: "felimarra9@gmail.com"
  SMTP_PASS: "pvyupflurbwcpfsp"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
